maintainer       "ReportGrid, Inc."
maintainer_email "operations@reportgrid.com"
license          "All rights reserved"
description      "Installs/Configures rgdeployer"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.2.5"
depends          "ruby"
depends          "postfix"
depends          "java"
depends          "reportgrid"
