maintainer       "ReportGrid"
maintainer_email "operations@reportgrid.com"
license          "All rights reserved"
description      "Installs/Configures reportgrid"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.2.13"
depends          "apache2"
depends          "java"
depends          "phantomjs"
depends          "s3tools"
depends          "subversion"
